// --- STATE MANAGEMENT ---
let hatchDatabase = [];

// App state defaults
const currentConditions = {
  biome: "Northeast",
  month: new Date().getMonth() + 1, // 1-12 range
  waterTemp: 55,
  waterType: "freestone"
};

// --- INITIALIZE APPLICATION ---
document.addEventListener("DOMContentLoaded", async () => {
  try {
    // Load the 101+ fly database generated by generate_hatches.cjs
    const response = await fetch('/hatches.json');
    if (!response.ok) throw new Error("Could not fetch hatches.json");
    
    hatchDatabase = await response.json();
    console.log("✓ Hatch database loaded successfully. Total profiles:", hatchDatabase.length);
    
    // Bind UI controls
    setupEventListeners();
    
    // Initial calculation for default screen load
    matchTheHatch();
  } catch (error) {
    console.error("❌ Critical error loading hatch database:", error);
  }
});

// --- UI INTERACTION BOUNDS ---
function setupEventListeners() {
  // Global mapping function for the rise buttons
  window.selectRise = (waterType, assumedTemp) => {
    currentConditions.waterType = waterType;
    if (assumedTemp) currentConditions.waterTemp = assumedTemp;
    
    // Trigger the matching filter engine
    matchTheHatch();
  };

  // Event bindings for manual condition overrides (if present in your HTML)
  const biomeSelector = document.getElementById("biome-select");
  const monthSelector = document.getElementById("month-select");
  
  if (biomeSelector) {
    biomeSelector.addEventListener("change", (e) => {
      currentConditions.biome = e.target.value;
      matchTheHatch();
    });
  }
  
  if (monthSelector) {
    monthSelector.addEventListener("change", (e) => {
      currentConditions.month = Number(e.target.value);
      matchTheHatch();
    });
  }
}

// --- CORE MATCH-THE-HATCH FILTER ENGINE ---
function matchTheHatch() {
  const { biome, month, waterTemp, waterType } = currentConditions;

  // Flattened property filters mapped to our exact database schema
  const matchedFlies = hatchDatabase.filter(hatch => {
    // 1. Biome Check
    const biomes = hatch.biomes || [];
    const biomeMatch = biomes.map(b => b.toLowerCase().trim()).includes(biome.toLowerCase().trim());

    // 2. Lifecycle Month Check
    const months = hatch.months || [];
    const monthMatch = months.includes(month);

    // 3. Ambient Water Temperature Window Check
    const minTemp = hatch.water_temp_range?.min_f ?? 32;
    const maxTemp = hatch.water_temp_range?.max_f ?? 80;
    const tempMatch = waterTemp >= minTemp && waterTemp <= maxTemp;

    // 4. Hydrographic Water Type Check
    const waterTypes = hatch.water_types || [];
    const waterTypeMatch = waterTypes.map(w => w.toLowerCase().trim()).includes(waterType.toLowerCase().trim());

    return biomeMatch && monthMatch && tempMatch && waterTypeMatch;
  });

  // Render out the matched results to the viewport layout grid
  renderResults(matchedFlies);
}

// --- RENDER PATTERNS TO THE VIEWPORT ---
function renderResults(flies) {
  const resultsContainer = document.getElementById("hatch-results-grid");
  if (!resultsContainer) return;

  if (flies.length === 0) {
    resultsContainer.innerHTML = `
      <div class="col-span-full text-center py-8 text-gray-400 border border-dashed border-gray-700 rounded-lg">
        <p class="text-lg font-medium">No active hatches matching current stream dynamics.</p>
        <p class="text-sm text-gray-500 mt-1">Try swinging an all-season attractor pattern or checking structural seams.</p>
      </div>
    `;
    return;
  }

  resultsContainer.innerHTML = flies.map(fly => {
    const sizeString = fly.size_range && fly.size_range.length > 0 
      ? `Sizes: #${fly.size_range.join(', #')}` 
      : 'Universal Size';

    return `
      <div class="p-4 bg-gray-800 border border-gray-700 rounded-xl shadow-md hover:border-emerald-500 transition-all duration-200">
        <div class="flex justify-between items-start">
          <div>
            <h3 class="text-white font-semibold text-base">${fly.name}</h3>
            <p class="text-xs text-gray-400 italic mt-0.5">${fly.imitation_species}</p>
          </div>
          <span class="px-2 py-0.5 text-xs font-medium rounded-full bg-emerald-950 text-emerald-400 border border-emerald-800 uppercase tracking-wider">
            ${fly.stage}
          </span>
        </div>
        <div class="mt-3 pt-3 border-t border-gray-700 flex justify-between items-center text-xs text-gray-300">
          <span>${sizeString}</span>
          <span class="text-gray-400 text-[10px] bg-gray-900 px-2 py-1 rounded font-mono">${fly.id.toUpperCase()}</span>
        </div>
      </div>
    `;
  }).join('');
}
// Add this quick fallback wrapper to the bottom of src/main.js:
window.selectRegion = (regionName) => {
  currentConditions.biome = regionName;
  matchTheHatch();
};
// --- GEOLOCATION & BIOME MAPPING ---
window.detectLocation = () => {
  if (!navigator.geolocation) {
    console.error("Geolocation is not supported by this browser.");
    alert("Location services are not supported by your browser.");
    return;
  }

  console.log("Requesting streamside coordinates...");
  navigator.geolocation.getCurrentPosition(
    (position) => {
      const { latitude, longitude } = position.coords;
      console.log(`Coords resolved: Lat ${latitude}, Lon ${longitude}`);
      
      // Simple coordinate bounding box to assign a fallback biome
      // (You can replace this logic with a real reverse-geocoding API later)
      let detectedBiome = "Northeast"; 
      
      if (longitude < -105) {
        detectedBiome = "Rocky Mountain";
      } else if (longitude < -120) {
        detectedBiome = "Pacific Northwest";
      } else if (longitude > -90 && latitude < 38) {
        detectedBiome = "Southeast";
      } else if (longitude < -80 && longitude > -97) {
        detectedBiome = "Midwest";
      }

      console.log(`Banded location to biome: ${detectedBiome}`);
      currentConditions.biome = detectedBiome;
      
      // Update UI dropdown selector value if it exists on screen
      const biomeSelector = document.getElementById("biome-select");
      if (biomeSelector) biomeSelector.value = detectedBiome;

      // Force filter update
      matchTheHatch();
    },
    (error) => {
      console.error("Error detecting location, defaulting to Northeast:", error);
      // Fallback gracefully so the app stays functional
      currentConditions.biome = "Northeast";
      matchTheHatch();
    }
  );
};
// --- LEGACY HTML INTERFACE WRAPPERS ---

// Resolves line 151 reference error
window.selectRegion = (regionName) => {
  currentConditions.biome = regionName;
  matchTheHatch();
};

// Ensures selectRise can be invoked globally from anywhere in the DOM
const originalSelectRise = window.selectRise;
window.selectRise = (waterType, assumedTemp) => {
  if (typeof originalSelectRise === 'function') {
    originalSelectRise(waterType, assumedTemp);
  } else {
    currentConditions.waterType = waterType;
    if (assumedTemp) currentConditions.waterTemp = assumedTemp;
    matchTheHatch();
  }
};
