// ============================================================================
// 1. GLOBAL STATE MANAGEMENT
// ============================================================================
let hatchDatabase = [];

// Fallback runtime conditions (Maps to our 101-fly flat schema rules)
const currentConditions = {
  biome: "Northeast",
  month: new Date().getMonth() + 1, // Normalized 1-12 range
  waterTemp: 55,
  waterType: "freestone"
};

// ============================================================================
// 2. CORE APPLICATION INITIALIZATION
// ============================================================================
document.addEventListener("DOMContentLoaded", async () => {
  try {
    // Fetch the 101+ fly database generated by generate_hatches.cjs
    const response = await fetch('/hatches.json');
    if (!response.ok) throw new Error("Could not fetch hatches.json asset profile");
    
    hatchDatabase = await response.json();
    console.log("✓ Hatch database loaded successfully. Total profiles:", hatchDatabase.length);
    
    // Bind manual inputs and standard controls
    setupEventListeners();
    
    // Evaluate initial baseline filter matching
    matchTheHatch();
  } catch (error) {
    console.error("❌ Critical error bootstrapping hatch engine:", error);
  }
});

// ============================================================================
// 3. UI EVENT LISTENER MAPPINGS
// ============================================================================
function setupEventListeners() {
  // Catch updates from manual UI select dropdowns if they exist in DOM
  const biomeSelector = document.getElementById("biome-select");
  const monthSelector = document.getElementById("month-select");
  
  if (biomeSelector) {
    biomeSelector.addEventListener("change", (e) => {
      currentConditions.biome = e.target.value;
      matchTheHatch();
    });
  }
  
  if (monthSelector) {
    monthSelector.addEventListener("change", (e) => {
      currentConditions.month = Number(e.target.value);
      matchTheHatch();
    });
  }
}

// ============================================================================
// 4. CORE MATCH-THE-HATCH FILTERING ENGINE
// ============================================================================
function matchTheHatch() {
  const { biome, month, waterTemp, waterType } = currentConditions;

  const matchedFlies = hatchDatabase.filter(hatch => {
    // 1. Biome Validation
    const biomes = hatch.biomes || [];
    const biomeMatch = biomes.map(b => b.toLowerCase().trim()).includes(biome.toLowerCase().trim());

    // 2. Chronological Hatch Window Check
    const months = hatch.months || [];
    const monthMatch = months.includes(month);

    // 3. Ambient Water Temperature Window Check
    const minTemp = hatch.water_temp_range?.min_f ?? 32;
    const maxTemp = hatch.water_temp_range?.max_f ?? 80;
    const tempMatch = waterTemp >= minTemp && waterTemp <= maxTemp;

    // 4. Hydrographic Stream Profile Match
    const waterTypes = hatch.water_types || [];
    const waterTypeMatch = waterTypes.map(w => w.toLowerCase().trim()).includes(waterType.toLowerCase().trim());

    return biomeMatch && monthMatch && tempMatch && waterTypeMatch;
  });

  // Render processed profiles out to the viewport
  renderResults(matchedFlies);
}

// ============================================================================
// 5. VIEWPORT DOM LAYOUT RENDERING
// ============================================================================
function renderResults(flies) {
  const resultsContainer = document.getElementById("hatch-results-grid");
  if (!resultsContainer) return;

  if (flies.length === 0) {
    resultsContainer.innerHTML = `
      <div class="col-span-full text-center py-8 text-gray-400 border border-dashed border-gray-700 rounded-lg">
        <p class="text-lg font-medium">No active hatches matching current stream dynamics.</p>
        <p class="text-sm text-gray-500 mt-1">Try swinging an all-season attractor pattern or checking structural seams.</p>
      </div>
    `;
    return;
  }

  resultsContainer.innerHTML = flies.map(fly => {
    const sizeString = fly.size_range && fly.size_range.length > 0 
      ? `Sizes: #${fly.size_range.join(', #')}` 
      : 'Universal Size';

    return `
      <div class="p-4 bg-gray-800 border border-gray-700 rounded-xl shadow-md hover:border-emerald-500 transition-all duration-200">
        <div class="flex justify-between items-start">
          <div>
            <h3 class="text-white font-semibold text-base">${fly.name}</h3>
            <p class="text-xs text-gray-400 italic mt-0.5">${fly.imitation_species}</p>
          </div>
          <span class="px-2 py-0.5 text-xs font-medium rounded-full bg-emerald-950 text-emerald-400 border border-emerald-800 uppercase tracking-wider">
            ${fly.stage}
          </span>
        </div>
        <div class="mt-3 pt-3 border-t border-gray-700 flex justify-between items-center text-xs text-gray-300">
          <span>${sizeString}</span>
          <span class="text-gray-400 text-[10px] bg-gray-900 px-2 py-1 rounded font-mono">${fly.id.toUpperCase()}</span>
        </div>
      </div>
    `;
  }).join('');
}

// ============================================================================
// 6. UI SCREEN TRANSITION ENGINE
// ============================================================================
function transitionToResultsView() {
  // Aggressively scan DOM for structural screen layout wrappers matching standard naming variants
  const setupScreen = document.getElementById("destination-screen") || 
                      document.getElementById("setup-view") || 
                      document.getElementById("region-selector-container") ||
                      document.querySelector(".destination-picker-wrapper"); // Fallback fallback selector
                           
  const appLayout = document.getElementById("main-app-layout") || 
                    document.getElementById("app-view") || 
                    document.getElementById("hatch-results-grid")?.parentElement;

  if (setupScreen && appLayout) {
    // Hide onboarding panel and expose the application lifecycle grid
    setupScreen.style.display = "none";
    setupScreen.classList.add("hidden", "d-none"); 

    appLayout.style.display = "block";
    appLayout.classList.remove("hidden", "d-none");
    console.log("✈️ UI Screen transition navigated to active stream view.");
  } else {
    console.warn("⚠️ Screen transition triggered, but matching DOM wrapper IDs weren't found.");
  }
}

// ============================================================================
// 7. GLOBAL WINDOW WINDOW BOUND INTERFACE WRAPPERS (LEGACY HTML TRIGGERS)
// ============================================================================

// HTML onClick -> detectLocation()
window.detectLocation = () => {
  if (!navigator.geolocation) {
    alert("Location services are not supported by your browser configuration.");
    return;
  }

  console.log("Requesting streamside coordinates...");
  navigator.geolocation.getCurrentPosition(
    (position) => {
      const { latitude, longitude } = position.coords;
      console.log(`Coords resolved: Lat ${latitude}, Lon ${longitude}`);
      
      let detectedBiome = "Northeast"; 
      
      // Basic bounding box estimation to automatically snap regional data
      if (longitude < -105) detectedBiome = "Rocky Mountain";
      else if (longitude < -120) detectedBiome = "Pacific Northwest";
      else if (longitude > -90 && latitude < 38) detectedBiome = "Southeast";
      else if (longitude < -80 && longitude > -97) detectedBiome = "Midwest";

      console.log(`Banded location to biome: ${detectedBiome}`);
      currentConditions.biome = detectedBiome;
      
      const biomeSelector = document.getElementById("biome-select");
      if (biomeSelector) biomeSelector.value = detectedBiome;

      matchTheHatch();
      transitionToResultsView();
    },
    (error) => {
      console.error("Error detecting location, defaulting to Northeast:", error);
      currentConditions.biome = "Northeast";
      matchTheHatch();
      transitionToResultsView();
    }
  );
};

// HTML onClick -> selectRegion('Northeast')
window.selectRegion = (regionName) => {
  if (!regionName) return;
  console.log(`Manual region selection registered: ${regionName}`);
  currentConditions.biome = regionName;
  
  const biomeSelector = document.getElementById("biome-select");
  if (biomeSelector) biomeSelector.value = regionName;

  matchTheHatch();
  transitionToResultsView();
};

// HTML onClick -> selectRise('freestone', 58)
window.selectRise = (waterType, assumedTemp) => {
  console.log(`Rise strategy assigned: ${waterType}, Target Temp: ${assumedTemp || 'No Change'}`);
  currentConditions.waterType = waterType;
  if (assumedTemp) currentConditions.waterTemp = assumedTemp;
  
  matchTheHatch();
  transitionToResultsView();
};
