// ============================================================================
// 1. GLOBAL STATE MANAGEMENT
// ============================================================================
let hatchDatabase = [];

// Fallback runtime conditions (Maps to our 101-fly flat schema rules)
const currentConditions = {
  biome: "Northeast",
  month: new Date().getMonth() + 1, // Normalized 1-12 range
  waterTemp: 55,
  waterType: "freestone"
};

// ============================================================================
// 2. CORE APPLICATION INITIALIZATION
// ============================================================================
document.addEventListener("DOMContentLoaded", async () => {
  try {
    // Fetch the 101+ fly database generated by generate_hatches.cjs
    const response = await fetch('/hatches.json');
    if (!response.ok) throw new Error("Could not fetch hatches.json asset profile");
    
    hatchDatabase = await response.json();
    console.log("✓ Hatch database loaded successfully. Total profiles:", hatchDatabase.length);
    
    // Bind manual inputs and standard controls
    setupEventListeners();
    
    // Evaluate initial baseline filter matching
    matchTheHatch();
  } catch (error) {
    console.error("❌ Critical error bootstrapping hatch engine:", error);
  }
});

// ============================================================================
// 3. UI EVENT LISTENER MAPPINGS
// ============================================================================
function setupEventListeners() {
  // Catch updates from manual UI select dropdowns if they exist in DOM
  const biomeSelector = document.getElementById("biome-select");
  const monthSelector = document.getElementById("month-select");
  
  if (biomeSelector) {
    biomeSelector.addEventListener("change", (e) => {
      currentConditions.biome = e.target.value;
      matchTheHatch();
    });
  }
  
  if (monthSelector) {
    monthSelector.addEventListener("change", (e) => {
      currentConditions.month = Number(e.target.value);
      matchTheHatch();
    });
  }
}

// ============================================================================
// 4. CORE MATCH-THE-HATCH FILTERING ENGINE
// ============================================================================
function matchTheHatch() {
  const { biome, month, waterTemp, waterType } = currentConditions;

  const matchedFlies = hatchDatabase.filter(hatch => {
    // 1. Biome Validation
    const biomes = hatch.biomes || [];
    const biomeMatch = biomes.map(b => b.toLowerCase().trim()).includes(biome.toLowerCase().trim());

    // 2. Chronological Hatch Window Check
    const months = hatch.months || [];
    const monthMatch = months.includes(month);

    // 3. Ambient Water Temperature Window Check
    const minTemp = hatch.water_temp_range?.min_f ?? 32;
    const maxTemp = hatch.water_temp_range?.max_f ?? 80;
    const tempMatch = waterTemp >= minTemp && waterTemp <= maxTemp;

    // 4. Hydrographic Stream Profile Match
    const waterTypes = hatch.water_types || [];
    const waterTypeMatch = waterTypes.map(w => w.toLowerCase().trim()).includes(waterType.toLowerCase().trim());

    return biomeMatch && monthMatch && tempMatch && waterTypeMatch;
  });

  // Render processed profiles out to the viewport
  renderResults(matchedFlies);
}

// ============================================================================
// 5. VIEWPORT DOM LAYOUT RENDERING
// ============================================================================
function renderResults(flies) {
  const resultsContainer = document.getElementById("hatch-results-grid");
  if (!resultsContainer) return;

  if (flies.length === 0) {
    resultsContainer.innerHTML = `
      <div class="col-span-full text-center py-8 text-gray-400 border border-dashed border-gray-700 rounded-lg">
        <p class="text-lg font-medium">No active hatches matching current stream dynamics.</p>
        <p class="text-sm text-gray-500 mt-1">Try swinging an all-season attractor pattern or checking structural seams.</p>
      </div>
    `;
    return;
  }

  resultsContainer.innerHTML = flies.map(fly => {
    const sizeString = fly.size_range && fly.size_range.length > 0 
      ? `Sizes: #${fly.size_range.join(', #')}` 
      : 'Universal Size';

    return `
      <div class="p-4 bg-gray-800 border border-gray-700 rounded-xl shadow-md hover:border-emerald-500 transition-all duration-200">
        <div class="flex justify-between items-start">
          <div>
            <h3 class="text-white font-semibold text-base">${fly.name}</h3>
            <p class="text-xs text-gray-400 italic mt-0.5">${fly.imitation_species}</p>
          </div>
          <span class="px-2 py-0.5 text-xs font-medium rounded-full bg-emerald-950 text-emerald-400 border border-emerald-800 uppercase tracking-wider">
            ${fly.stage}
          </span>
        </div>
        <div class="mt-3 pt-3 border-t border-gray-700 flex justify-between items-center text-xs text-gray-300">
          <span>${sizeString}</span>
          <span class="text-gray-400 text-[10px] bg-gray-900 px-2 py-1 rounded font-mono">${fly.id.toUpperCase()}</span>
        </div>
      </div>
    `;
  }).join('');
}
// ============================================================================
// 6. UI SCREEN TRANSITION ENGINE (MULTI-STEP WIZARD)
// ============================================================================
function advanceToNextScreen(currentScreenId, nextScreenId) {
  const currentScreen = document.getElementById(currentScreenId);
  const nextScreen = document.getElementById(nextScreenId);

  if (currentScreen && nextScreen) {
    // Remove active class from the current step to hide it
    currentScreen.classList.remove("active");
    // Add active class to the next step to reveal it
    nextScreen.classList.add("active");
    console.log(`✈️ Advanced UI: ${currentScreenId} -> ${nextScreenId}`);
  } else {
    // Fallback if direct multi-step tags aren't perfectly aligned
    console.warn(`⚠️ Wizard transition requested for missing elements: ${currentScreenId} or ${nextScreenId}`);
  }
}

// ============================================================================
// 7. GLOBAL WINDOW INTERFACE WRAPPERS (MATCHING YOUR INDEX.HTML)
// ============================================================================

// Automated streamside detection
window.detectLocation = () => {
  if (!navigator.geolocation) {
    alert("Location services are not supported by your browser configuration.");
    return;
  }

  const gpsStatus = document.getElementById("gps-status");
  if (gpsStatus) {
    gpsStatus.style.display = "block";
    gpsStatus.innerText = "🛰️ Resolving stream coordinates...";
  }

  navigator.geolocation.getCurrentPosition(
    (position) => {
      const { latitude, longitude } = position.coords;
      let detectedBiome = "appalachian"; // Default fallback to PA limestone country
      
      // Coordinate mapping tailored to your specific biome keys
      if (longitude < -105) {
        detectedBiome = "rocky_mountain";
      } else if (longitude < -120) {
        detectedBiome = "pacific_coastal";
      } else if (longitude < -80 && longitude > -97) {
        detectedBiome = "boreal_shield";
      } else if (latitude < 36) {
        detectedBiome = "warmwater_south";
      }

      console.log(`Banded location to biome: ${detectedBiome}`);
      currentConditions.biome = detectedBiome;
      
      if (gpsStatus) gpsStatus.innerText = `🛰️ Locked: ${detectedBiome.toUpperCase()}`;

      matchTheHatch();
      
      // Progress past the region selection to the environment screen
      setTimeout(() => {
        advanceToNextScreen("step-region", "step-environment");
      }, 800);
    },
    (error) => {
      console.error("Error detecting location, defaulting to appalachian:", error);
      currentConditions.biome = "appalachian";
      matchTheHatch();
      advanceToNextScreen("step-region", "step-environment");
    }
  );
};

// Manual region button selection handler
window.selectRegion = (regionName) => {
  if (!regionName) return;
  console.log(`Manual region selection registered: ${regionName}`);
  
  // Set the core tracking state to the exact string passed by your button
  currentConditions.biome = regionName;

  // Run the filter calculations
  matchTheHatch();
  
  // Smoothly slide the user from step-region into step-environment
  advanceToNextScreen("step-region", "step-environment");
};

// Manual environment button selection handler (River vs Lake)
window.selectEnvironment = (envType) => {
  if (!envType) return;
  console.log(`Manual environment selection registered: ${envType}`);
  
  // Map the HTML choice over to our tracking states
  // if it's lake/pond, we swap the water type default over to stillwater
  if (envType === 'lake_pond') {
    currentConditions.waterType = "stillwater";
  } else {
    currentConditions.waterType = "freestone"; // baseline default for moving water
  }

  // Recalculate match filtering
  matchTheHatch();
  
  // Advance the wizard to the target species panel
  advanceToNextScreen("step-environment", "step-species");
};

// Manual species targeting selection handler
window.selectSpecies = (speciesName) => {
  if (!speciesName) return;
  console.log(`Target species selection registered: ${speciesName}`);
  
  // Stash species in state if you choose to filter by fish classification later
  currentConditions.targetSpecies = speciesName;

  // Recalculate match filtering rules
  matchTheHatch();
  
  // Step the wizard forward to the temperature configuration panel
  advanceToNextScreen("step-species", "step-temp");
};

// Handles submission from the temperature slider panel
window.submitTemp = () => {
  const tempSlider = document.getElementById("temp-slider");
  if (!tempSlider) {
    console.warn("⚠️ Temperature slider element not found in DOM.");
    // Fallback and advance anyway if the element is missing
    advanceToNextScreen("step-temp", "step-water");
    return;
  }

  const selectedValue = Number(tempSlider.value);
  console.log(`Water temperature submitted: ${selectedValue}°F`);

  // Assign the dynamic temperature to our core filter state
  currentConditions.waterTemp = selectedValue;

  // Run the calculations across the 101 profiles
  matchTheHatch();

  // Advance the wizard to the water speed/type screen
  advanceToNextScreen("step-temp", "step-water");
};

// Global inline slider tracking fallback wrapper
window.updateTempDisplay = (value) => {
  const display = document.getElementById("temp-display");
  if (display) display.innerText = `${value}°F`;
};

// Fallback matching logic for direct rise inputs
window.selectRise = (waterType, assumedTemp) => {
  console.log(`Rise strategy assigned: ${waterType}`);
  currentConditions.waterType = waterType;
  if (assumedTemp) currentConditions.waterTemp = assumedTemp;
  
  matchTheHatch();
};
